name: exotic-oses

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

jobs:
  exotic-os-python-tests:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Setup Python development environment
        run: |
          # Use smallest supported Python version as the common denominator.
          # In theory, if everything succeed in 3.10, everything should succeed in
          # 3.11, 3.12, 3.13 and follow-up version.
          uv sync --group all --python "3.10"
      # Perform type checking before testing because that is quicker.
      - name: Type checking
        run: uv run ty check
      # Only perform quick tests to avoid paying too much minutes on that.
      - name: Partial tests
        run: uv run pytest $(git ls-files '*_test.py') -m "not slow"
